# .platform/app.yaml
# Define the application-level configuration
app:
  name: chatbot-api
  type: python3.8
  disk: 1024
  web:
    entrypoint: uvicorn api:app --host 0.0.0.0 --port 8000
  relationships:
    api: api
