# .platform/services.yaml
# Define services (containers or processes) that make up the application
# Example:
# services:
#   api:
#     type: web
#     command: uvicorn api:app --host 0.0.0.0 --port 8000
#     build: .
#     resources:
#       cpu: 1
#       memory: 512MB
